stages:
  - formatting
  - checks
  - debug build
  - release build
  - static analysis
  - integration tests

default:
  interruptible: true

include:
  - /.gitlab/ci/checks.yml
  - /.gitlab/ci/builds.yml
  - /.gitlab/ci/tests.yml
  - /.gitlab/ci/rules.yml
