#!/bin/bash

trap exit ERR

function encode() {
    scripts/test/encode_conformance_bitstream.py \
        -u git@github.com:philips-internal/immersive-video-mpeg-test-model.git \
        --mail-user bart.kroon@philips.com \
        --env-files /home/videssa/sw/enable/gcc-12.2.0 \
        -j 8 \
        --sbatch \
        -i $1
}

for id in CB01 CB02 CB03 CB04 CB05.1 CB05.2 CB05.3 CB06 CB07.1 CB07.2 CB07.3 CB08 CB09 CB10 CB11 CB14 CB15 CB16 CB17 CB18 CB19 CB20
do
    encode $id
done
